[package]
name = "free_var"
version = "0.1.0"
authors = ["leon2k2k2k <liuleon4@gmail.com>", "a dummy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
