# this builds the rust package.

on: [push]

name: build

jobs: 
  build:
    name: Aplite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build 
      - uses: actions/upload-artifact@main
        with: 
          name: Aplite 
          path: public/
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@main
        with: 
          name: Aplite
          path: public
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: 
          profile: minimal 
          toolchain: stable
          override: true 

      - naem: Run cargo test 
        uses: actions-rs/cargo@v1
        with:
          command: test
